<?php
/**
 * Forma – Root .htaccess builder.
 */
class Htaccess {
    public static function defaultContent(): string {
        return <<<'HTA'
# Generated by Forma
RewriteEngine On

# BEGIN Forma static fallback
# Last-good HTML so Apache can still serve the homepage if PHP/FastCGI dies
# (DreamHost “No input file specified.”). GET /up always hits PHP so monitors can tell.
RewriteCond %{REQUEST_METHOD} GET
RewriteCond %{QUERY_STRING} !preview
RewriteCond %{HTTP_HOST} !^preview\.
RewriteCond %{REQUEST_URI} !/up(/|$)
RewriteCond %{REQUEST_URI} !/admin(/|$)
RewriteCond %{REQUEST_URI} !/api/
RewriteCond %{DOCUMENT_ROOT}/fallback/index.html -f
RewriteRule ^$ fallback/index.html [L]

# Inner last-good pages only during an outage (touch fallback/.php-down)
RewriteCond %{REQUEST_METHOD} GET
RewriteCond %{QUERY_STRING} !preview
RewriteCond %{HTTP_HOST} !^preview\.
RewriteCond %{DOCUMENT_ROOT}/fallback/.php-down -f
RewriteCond %{REQUEST_URI} !/up(/|$)
RewriteCond %{REQUEST_URI} !/admin(/|$)
RewriteCond %{REQUEST_URI} !/api/
RewriteCond %{DOCUMENT_ROOT}/fallback/$1.html -f
RewriteRule ^(.+)$ fallback/$1.html [L]
# END Forma static fallback

# DreamHost / CGI / FastCGI strip Authorization — pass it through to PHP
RewriteCond %{HTTP:Authorization} .
RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]

# Always serve SEO files via Forma (ignore leftover static robots.txt / sitemap.xml)
RewriteRule ^robots\.txt$ /index.php [L]
RewriteRule ^sitemap\.xml$ /index.php [L]

# Never rewrite existing .php — empty SCRIPT_FILENAME on some CGI vhosts
RewriteRule \.php$ - [L]

RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /index.php [L,QSA]

<IfModule mod_rewrite.c>
    RewriteRule ^database/ - [F,L]
    RewriteRule ^lib/ - [F,L]
    RewriteRule ^mcp/ - [F,L]
    RewriteRule ^tools/ - [F,L]
</IfModule>

<FilesMatch "\.(db|sqlite|log|sh|sql|bak|env|ini)$">
    Require all denied
</FilesMatch>

<IfModule mod_rewrite.c>
    RewriteRule ^uploads/.*\.php$ - [F,L]
</IfModule>

<IfModule mod_headers.c>
    Header set X-Content-Type-Options "nosniff"
    Header set X-Frame-Options "SAMEORIGIN"
    Header set Referrer-Policy "strict-origin-when-cross-origin"
</IfModule>

Options -Indexes
ServerSignature Off
HTA;
    }

    public static function ensureDefault(): bool {
        $path = ROOT_DIR . '/.htaccess';
        if (file_exists($path)) {
            self::ensureSeoPassthrough();
            self::ensureStaticFallbackRules();
            self::ensureFastCgiSafeFrontController();
            return true;
        }
        return file_put_contents($path, self::defaultContent()) !== false;
    }

    public static function hasStaticFallbackRules(?string $content = null): bool {
        $content = $content ?? (is_file(ROOT_DIR . '/.htaccess') ? (string)file_get_contents(ROOT_DIR . '/.htaccess') : '');
        return str_contains($content, '# BEGIN Forma static fallback');
    }

    /**
     * Inject last-good HTML rules into an existing .htaccess (keeps PREVIEW / custom blocks).
     */
    public static function ensureStaticFallbackRules(): bool {
        $path = ROOT_DIR . '/.htaccess';
        if (!is_file($path) || !is_writable($path)) {
            return false;
        }
        $content = (string)file_get_contents($path);
        if (self::hasStaticFallbackRules($content)) {
            return true;
        }
        $block = self::staticFallbackBlock();
        if (preg_match('/RewriteEngine\s+On\s*\n/i', $content, $m, PREG_OFFSET_CAPTURE)) {
            $insertAt = $m[0][1] + strlen($m[0][0]);
            $content = substr($content, 0, $insertAt) . "\n" . $block . substr($content, $insertAt);
        } else {
            $content = $block . $content;
        }
        return file_put_contents($path, $content) !== false;
    }

    public static function staticFallbackBlock(): string {
        return <<<'HTA'
# BEGIN Forma static fallback
# Last-good HTML so Apache can still serve the homepage if PHP/FastCGI dies
# (DreamHost “No input file specified.”). GET /up always hits PHP so monitors can tell.
RewriteCond %{REQUEST_METHOD} GET
RewriteCond %{QUERY_STRING} !preview
RewriteCond %{HTTP_HOST} !^preview\.
RewriteCond %{REQUEST_URI} !/up(/|$)
RewriteCond %{REQUEST_URI} !/admin(/|$)
RewriteCond %{REQUEST_URI} !/api/
RewriteCond %{DOCUMENT_ROOT}/fallback/index.html -f
RewriteRule ^$ fallback/index.html [L]

# Inner last-good pages only during an outage (touch fallback/.php-down)
RewriteCond %{REQUEST_METHOD} GET
RewriteCond %{QUERY_STRING} !preview
RewriteCond %{HTTP_HOST} !^preview\.
RewriteCond %{DOCUMENT_ROOT}/fallback/.php-down -f
RewriteCond %{REQUEST_URI} !/up(/|$)
RewriteCond %{REQUEST_URI} !/admin(/|$)
RewriteCond %{REQUEST_URI} !/api/
RewriteCond %{DOCUMENT_ROOT}/fallback/$1.html -f
RewriteRule ^(.+)$ fallback/$1.html [L]
# END Forma static fallback

HTA;
    }

    /**
     * Prefer /index.php and do not rewrite existing .php (DreamHost empty SCRIPT_FILENAME).
     */
    public static function ensureFastCgiSafeFrontController(): bool {
        $path = ROOT_DIR . '/.htaccess';
        if (!is_file($path) || !is_writable($path)) {
            return false;
        }
        $content = (string)file_get_contents($path);
        $changed = false;
        if (!preg_match('/RewriteRule\s+\\\\?\.php\$\s+-\s+\[L\]/i', $content)) {
            $skip = "RewriteRule \\.php$ - [L]\n\n";
            if (preg_match('/RewriteCond\s+%\{REQUEST_FILENAME\}\s+!-f\s*\n/i', $content, $m, PREG_OFFSET_CAPTURE)) {
                $insertAt = $m[0][1];
                $content = substr($content, 0, $insertAt) . $skip . substr($content, $insertAt);
                $changed = true;
            }
        }
        if (preg_match('/RewriteRule\s+\^\s+index\.php(\s+\[L\])?/i', $content)) {
            $content = preg_replace(
                '/RewriteRule\s+\^\s+index\.php(\s+\[L\])?/i',
                'RewriteRule . /index.php [L,QSA]',
                $content,
                1
            );
            $changed = true;
        }
        if (!$changed) {
            return true;
        }
        return file_put_contents($path, $content) !== false;
    }

    /**
     * Inject robots/sitemap → index.php rules into an existing .htaccess if missing.
     */
    public static function ensureSeoPassthrough(): bool {
        $path = ROOT_DIR . '/.htaccess';
        if (!is_file($path) || !is_writable($path)) {
            return false;
        }
        $content = (string)file_get_contents($path);
        if (preg_match('/RewriteRule\s+\^robots\\\\\.txt\$/i', $content)) {
            return true;
        }
        $block = "# Always serve SEO files via Forma (ignore leftover static robots.txt / sitemap.xml)\n"
            . "RewriteRule ^robots\\.txt$ index.php [L]\n"
            . "RewriteRule ^sitemap\\.xml$ index.php [L]\n\n";
        if (preg_match('/RewriteCond\s+%\{HTTP:Authorization\}[^\n]*\nRewriteRule[^\n]+\n/i', $content, $m, PREG_OFFSET_CAPTURE)) {
            $insertAt = $m[0][1] + strlen($m[0][0]);
            $content = substr($content, 0, $insertAt) . "\n" . $block . substr($content, $insertAt);
        } elseif (preg_match('/RewriteEngine\s+On\s*\n/i', $content, $m, PREG_OFFSET_CAPTURE)) {
            $insertAt = $m[0][1] + strlen($m[0][0]);
            $content = substr($content, 0, $insertAt) . "\n" . $block . substr($content, $insertAt);
        } else {
            $content = $block . $content;
        }
        return file_put_contents($path, $content) !== false;
    }

    public static function write(string $content): bool {
        return file_put_contents(ROOT_DIR . '/.htaccess', $content) !== false;
    }

    public static function hasSeoPassthrough(?string $content = null): bool {
        $content = $content ?? (is_file(ROOT_DIR . '/.htaccess') ? (string)file_get_contents(ROOT_DIR . '/.htaccess') : '');
        return (bool)preg_match('/RewriteRule\s+\^robots\\\\\.txt\$/i', $content);
    }

    /** @return array{robots:bool,sitemap:bool} Whether static files exist on disk (and would shadow Forma without rewrite rules). */
    public static function staticSeoFiles(): array {
        return [
            'robots'  => is_file(ROOT_DIR . '/robots.txt'),
            'sitemap' => is_file(ROOT_DIR . '/sitemap.xml'),
        ];
    }

    /**
     * Delete leftover static SEO files so Apache can't serve them over PHP.
     * @return array{ok:bool,removed:string[],errors:string[]}
     */
    public static function removeStaticSeoFiles(): array {
        $removed = [];
        $errors = [];
        foreach (['robots.txt', 'sitemap.xml'] as $name) {
            $path = ROOT_DIR . '/' . $name;
            if (!is_file($path)) {
                continue;
            }
            if (@unlink($path)) {
                $removed[] = $name;
            } else {
                $errors[] = "Could not delete {$name} (permissions?)";
            }
        }
        return [
            'ok' => $errors === [],
            'removed' => $removed,
            'errors' => $errors,
        ];
    }
}
