<?php
/**
 * Forma – Root .htaccess builder.
 */
class Htaccess {
    public static function defaultContent(): string {
        return <<<'HTA'
# Generated by Forma
RewriteEngine On

# BEGIN Forma static fallback
# HTML cache: Apache serves fallback/*.html directly when fallback/.enabled exists.
# A page that hasn't been published yet has no matching file, so it falls through
# to PHP below — a half-migrated site still works. GET /up, /admin, /api, /search,
# robots.txt/sitemap.xml/feeds always hit PHP so monitors + dynamic routes still work.
RewriteCond %{DOCUMENT_ROOT}/fallback/.enabled -f
RewriteCond %{REQUEST_METHOD} GET
RewriteCond %{QUERY_STRING} !preview
RewriteCond %{HTTP_HOST} !^preview\.
RewriteCond %{REQUEST_URI} !/up(/|$)
RewriteCond %{REQUEST_URI} !/admin(/|$)
RewriteCond %{REQUEST_URI} !/api/
RewriteCond %{REQUEST_URI} !/search(/|$)
RewriteCond %{REQUEST_URI} !^/(robots\.txt|sitemap\.xml|feed\.xml|feed\.json)$
RewriteCond %{REQUEST_URI} !/feeds/
RewriteCond %{DOCUMENT_ROOT}/fallback/index.html -f
RewriteRule ^$ fallback/index.html [L]

RewriteCond %{DOCUMENT_ROOT}/fallback/.enabled -f
RewriteCond %{REQUEST_METHOD} GET
RewriteCond %{QUERY_STRING} !preview
RewriteCond %{HTTP_HOST} !^preview\.
RewriteCond %{REQUEST_URI} !/up(/|$)
RewriteCond %{REQUEST_URI} !/admin(/|$)
RewriteCond %{REQUEST_URI} !/api/
RewriteCond %{REQUEST_URI} !/search(/|$)
RewriteCond %{REQUEST_URI} !^/(robots\.txt|sitemap\.xml|feed\.xml|feed\.json)$
RewriteCond %{REQUEST_URI} !/feeds/
RewriteCond %{DOCUMENT_ROOT}/fallback/$1.html -f
RewriteRule ^(.+)$ fallback/$1.html [L]
# END Forma static fallback

# DreamHost / CGI / FastCGI strip Authorization — pass it through to PHP
RewriteCond %{HTTP:Authorization} .
RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]

# Always serve SEO files via Forma (ignore leftover static robots.txt / sitemap.xml)
RewriteRule ^robots\.txt$ /index.php [L]
RewriteRule ^sitemap\.xml$ /index.php [L]

# Never rewrite existing .php — empty SCRIPT_FILENAME on some CGI vhosts
RewriteRule \.php$ - [L]

RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /index.php [L,QSA]

<IfModule mod_rewrite.c>
    RewriteRule ^database/ - [F,L]
    RewriteRule ^lib/ - [F,L]
    RewriteRule ^mcp/ - [F,L]
    RewriteRule ^tools/ - [F,L]
</IfModule>

<FilesMatch "\.(db|sqlite|log|sh|sql|bak|env|ini)$">
    Require all denied
</FilesMatch>

<IfModule mod_rewrite.c>
    RewriteRule ^uploads/.*\.php$ - [F,L]
</IfModule>

<IfModule mod_headers.c>
    Header set X-Content-Type-Options "nosniff"
    Header set X-Frame-Options "SAMEORIGIN"
    Header set Referrer-Policy "strict-origin-when-cross-origin"
</IfModule>

Options -Indexes
ServerSignature Off
HTA;
    }

    public static function ensureDefault(): bool {
        $path = ROOT_DIR . '/.htaccess';
        if (file_exists($path)) {
            self::ensureSeoPassthrough();
            self::ensureStaticFallbackRules();
            self::ensureFastCgiSafeFrontController();
            return true;
        }
        return file_put_contents($path, self::defaultContent()) !== false;
    }

    public static function hasStaticFallbackRules(?string $content = null): bool {
        $content = $content ?? (is_file(ROOT_DIR . '/.htaccess') ? (string)file_get_contents(ROOT_DIR . '/.htaccess') : '');
        return str_contains($content, '# BEGIN Forma static fallback');
    }

    /**
     * Inject publish-mode rules into an existing .htaccess (keeps PREVIEW / custom blocks).
     * Anchored after the redirects block when present so 301s always win over stale files.
     */
    public static function ensureStaticFallbackRules(): bool {
        $path = ROOT_DIR . '/.htaccess';
        if (!is_file($path) || !is_writable($path)) {
            return false;
        }
        $content = (string)file_get_contents($path);
        if (self::hasStaticFallbackRules($content)) {
            return true;
        }
        $block = self::staticFallbackBlock();
        $insertAt = null;
        if (preg_match('/# END Forma redirects\s*\n/i', $content, $m, PREG_OFFSET_CAPTURE)) {
            $insertAt = $m[0][1] + strlen($m[0][0]);
        } elseif (preg_match('/RewriteEngine\s+On\s*\n/i', $content, $m, PREG_OFFSET_CAPTURE)) {
            $insertAt = $m[0][1] + strlen($m[0][0]);
        }
        if ($insertAt !== null) {
            $content = substr($content, 0, $insertAt) . "\n" . $block . substr($content, $insertAt);
        } else {
            $content = $block . $content;
        }
        return file_put_contents($path, $content) !== false;
    }

    public static function staticFallbackBlock(): string {
        return <<<'HTA'
# BEGIN Forma static fallback
# HTML cache: Apache serves fallback/*.html directly when fallback/.enabled exists.
# A page that hasn't been published yet has no matching file, so it falls through
# to PHP below — a half-migrated site still works. GET /up, /admin, /api, /search,
# robots.txt/sitemap.xml/feeds always hit PHP so monitors + dynamic routes still work.
RewriteCond %{DOCUMENT_ROOT}/fallback/.enabled -f
RewriteCond %{REQUEST_METHOD} GET
RewriteCond %{QUERY_STRING} !preview
RewriteCond %{HTTP_HOST} !^preview\.
RewriteCond %{REQUEST_URI} !/up(/|$)
RewriteCond %{REQUEST_URI} !/admin(/|$)
RewriteCond %{REQUEST_URI} !/api/
RewriteCond %{REQUEST_URI} !/search(/|$)
RewriteCond %{REQUEST_URI} !^/(robots\.txt|sitemap\.xml|feed\.xml|feed\.json)$
RewriteCond %{REQUEST_URI} !/feeds/
RewriteCond %{DOCUMENT_ROOT}/fallback/index.html -f
RewriteRule ^$ fallback/index.html [L]

RewriteCond %{DOCUMENT_ROOT}/fallback/.enabled -f
RewriteCond %{REQUEST_METHOD} GET
RewriteCond %{QUERY_STRING} !preview
RewriteCond %{HTTP_HOST} !^preview\.
RewriteCond %{REQUEST_URI} !/up(/|$)
RewriteCond %{REQUEST_URI} !/admin(/|$)
RewriteCond %{REQUEST_URI} !/api/
RewriteCond %{REQUEST_URI} !/search(/|$)
RewriteCond %{REQUEST_URI} !^/(robots\.txt|sitemap\.xml|feed\.xml|feed\.json)$
RewriteCond %{REQUEST_URI} !/feeds/
RewriteCond %{DOCUMENT_ROOT}/fallback/$1.html -f
RewriteRule ^(.+)$ fallback/$1.html [L]
# END Forma static fallback

HTA;
    }

    /**
     * Prefer /index.php and do not rewrite existing .php (DreamHost empty SCRIPT_FILENAME).
     */
    public static function ensureFastCgiSafeFrontController(): bool {
        $path = ROOT_DIR . '/.htaccess';
        if (!is_file($path) || !is_writable($path)) {
            return false;
        }
        $content = (string)file_get_contents($path);
        $changed = false;
        if (!preg_match('/RewriteRule\s+\\\\?\.php\$\s+-\s+\[L\]/i', $content)) {
            $skip = "RewriteRule \\.php$ - [L]\n\n";
            if (preg_match('/RewriteCond\s+%\{REQUEST_FILENAME\}\s+!-f\s*\n/i', $content, $m, PREG_OFFSET_CAPTURE)) {
                $insertAt = $m[0][1];
                $content = substr($content, 0, $insertAt) . $skip . substr($content, $insertAt);
                $changed = true;
            }
        }
        if (preg_match('/RewriteRule\s+\^\s+index\.php(\s+\[L\])?/i', $content)) {
            $content = preg_replace(
                '/RewriteRule\s+\^\s+index\.php(\s+\[L\])?/i',
                'RewriteRule . /index.php [L,QSA]',
                $content,
                1
            );
            $changed = true;
        }
        if (!$changed) {
            return true;
        }
        return file_put_contents($path, $content) !== false;
    }

    /**
     * Inject robots/sitemap → index.php rules into an existing .htaccess if missing.
     */
    public static function ensureSeoPassthrough(): bool {
        $path = ROOT_DIR . '/.htaccess';
        if (!is_file($path) || !is_writable($path)) {
            return false;
        }
        $content = (string)file_get_contents($path);
        if (preg_match('/RewriteRule\s+\^robots\\\\\.txt\$/i', $content)) {
            return true;
        }
        $block = "# Always serve SEO files via Forma (ignore leftover static robots.txt / sitemap.xml)\n"
            . "RewriteRule ^robots\\.txt$ index.php [L]\n"
            . "RewriteRule ^sitemap\\.xml$ index.php [L]\n\n";
        if (preg_match('/RewriteCond\s+%\{HTTP:Authorization\}[^\n]*\nRewriteRule[^\n]+\n/i', $content, $m, PREG_OFFSET_CAPTURE)) {
            $insertAt = $m[0][1] + strlen($m[0][0]);
            $content = substr($content, 0, $insertAt) . "\n" . $block . substr($content, $insertAt);
        } elseif (preg_match('/RewriteEngine\s+On\s*\n/i', $content, $m, PREG_OFFSET_CAPTURE)) {
            $insertAt = $m[0][1] + strlen($m[0][0]);
            $content = substr($content, 0, $insertAt) . "\n" . $block . substr($content, $insertAt);
        } else {
            $content = $block . $content;
        }
        return file_put_contents($path, $content) !== false;
    }

    public static function write(string $content): bool {
        return file_put_contents(ROOT_DIR . '/.htaccess', $content) !== false;
    }

    public static function hasSeoPassthrough(?string $content = null): bool {
        $content = $content ?? (is_file(ROOT_DIR . '/.htaccess') ? (string)file_get_contents(ROOT_DIR . '/.htaccess') : '');
        return (bool)preg_match('/RewriteRule\s+\^robots\\\\\.txt\$/i', $content);
    }

    /** @return array{robots:bool,sitemap:bool} Whether static files exist on disk (and would shadow Forma without rewrite rules). */
    public static function staticSeoFiles(): array {
        return [
            'robots'  => is_file(ROOT_DIR . '/robots.txt'),
            'sitemap' => is_file(ROOT_DIR . '/sitemap.xml'),
        ];
    }

    /**
     * Delete leftover static SEO files so Apache can't serve them over PHP.
     * @return array{ok:bool,removed:string[],errors:string[]}
     */
    public static function removeStaticSeoFiles(): array {
        $removed = [];
        $errors = [];
        foreach (['robots.txt', 'sitemap.xml'] as $name) {
            $path = ROOT_DIR . '/' . $name;
            if (!is_file($path)) {
                continue;
            }
            if (@unlink($path)) {
                $removed[] = $name;
            } else {
                $errors[] = "Could not delete {$name} (permissions?)";
            }
        }
        return [
            'ok' => $errors === [],
            'removed' => $removed,
            'errors' => $errors,
        ];
    }

    // ---- Error documents (Apache-level, survive a dead FastCGI) ----------

    public static function hasErrorDocuments(?string $content = null): bool {
        $content = $content ?? (is_file(ROOT_DIR . '/.htaccess') ? (string)file_get_contents(ROOT_DIR . '/.htaccess') : '');
        return str_contains($content, '# BEGIN Forma error documents');
    }

    public static function errorDocumentsBlock(): string {
        return <<<'HTA'
# BEGIN Forma error documents
# Served by Apache itself — still works when PHP/FastCGI is completely down.
ErrorDocument 404 /fallback/_404.html
ErrorDocument 403 /fallback/_403.html
ErrorDocument 500 /fallback/_500.html
# END Forma error documents

HTA;
    }

    public static function ensureErrorDocuments(bool $on): bool {
        $path = ROOT_DIR . '/.htaccess';
        if (!is_file($path) || !is_writable($path)) {
            return false;
        }
        $content = (string)file_get_contents($path);
        $has = self::hasErrorDocuments($content);
        if ($on === $has) {
            return true;
        }
        if ($on) {
            $block = self::errorDocumentsBlock();
            if (preg_match('/# END Forma static fallback\s*\n/i', $content, $m, PREG_OFFSET_CAPTURE)) {
                $insertAt = $m[0][1] + strlen($m[0][0]);
                $content = substr($content, 0, $insertAt) . "\n" . $block . substr($content, $insertAt);
            } elseif (preg_match('/RewriteEngine\s+On\s*\n/i', $content, $m, PREG_OFFSET_CAPTURE)) {
                $insertAt = $m[0][1] + strlen($m[0][0]);
                $content = substr($content, 0, $insertAt) . "\n" . $block . substr($content, $insertAt);
            } else {
                $content = $block . $content;
            }
        } else {
            $content = (string)preg_replace('/# BEGIN Forma error documents.*?# END Forma error documents\s*\n?/s', '', $content);
        }
        return file_put_contents($path, $content) !== false;
    }

    // ---- Redirects (Apache-level 301s, written from Settings -> SEO) -----

    public static function hasRedirectsBlock(?string $content = null): bool {
        $content = $content ?? (is_file(ROOT_DIR . '/.htaccess') ? (string)file_get_contents(ROOT_DIR . '/.htaccess') : '');
        return str_contains($content, '# BEGIN Forma redirects');
    }

    private static function redirectRuleLine(array $r): ?string {
        $from = trim((string)($r['from_path'] ?? ''), '/');
        $to = trim((string)($r['to_url'] ?? ''));
        if ($from === '' || $to === '' || empty($r['enabled'])) {
            return null;
        }
        $status = (int)($r['status'] ?? 301);
        if (!in_array($status, [301, 302, 307, 308], true)) {
            $status = 301;
        }
        // Escape regex metacharacters for RewriteRule's ERE pattern; typical slugs need none of this.
        $pattern = '^' . preg_quote($from, '/') . '/?$';
        return "RewriteRule {$pattern} {$to} [R={$status},L]";
    }

    /**
     * Rewrites the whole redirects block from the current DB rows. Always anchored right
     * after "RewriteEngine On" so 301s take priority over both published files and PHP.
     */
    public static function syncRedirectsBlock(array $redirects): bool {
        $path = ROOT_DIR . '/.htaccess';
        if (!is_file($path) || !is_writable($path)) {
            return false;
        }
        $content = (string)file_get_contents($path);
        $lines = [];
        foreach ($redirects as $r) {
            $line = self::redirectRuleLine($r);
            if ($line !== null) {
                $lines[] = $line;
            }
        }
        $block = $lines
            ? "# BEGIN Forma redirects\n# Written from Settings -> SEO -> Redirects. Apache-level 301s survive PHP outages.\n"
                . implode("\n", $lines) . "\n# END Forma redirects\n\n"
            : '';
        if (self::hasRedirectsBlock($content)) {
            $content = (string)preg_replace('/# BEGIN Forma redirects.*?# END Forma redirects\s*\n?/s', $block, $content);
        } elseif ($block !== '') {
            if (preg_match('/RewriteEngine\s+On\s*\n/i', $content, $m, PREG_OFFSET_CAPTURE)) {
                $insertAt = $m[0][1] + strlen($m[0][0]);
                $content = substr($content, 0, $insertAt) . "\n" . $block . substr($content, $insertAt);
            } else {
                $content = $block . $content;
            }
        } else {
            return true;
        }
        return file_put_contents($path, $content) !== false;
    }
}
